# repo2: .github/workflows/call-reusable-workflow.yml
name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call_reusable_workflow:
    uses: user/repo1/.github/workflows/reusable-workflow.yml@main
    with:
      message: "Hello from repo2!"
