name: Consumer AEH Management

on:
  push:
    branches:
      - main 
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource Group Name'
        required: false
      project_name:
        description: 'Project Name'
        required: false
      aeh_name:
        description: 'AEH Name'
        required: false
      uaim:
        description: 'UAIM Hexadecimal Number'
        required: false

jobs:
  aeh_access:
    # if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.inputs.resource_group && github.event.inputs.project_name && github.event.inputs.aeh_name && github.event.inputs.uaim
    runs-on: ubuntu-latest
    steps:
      - name: AEH Access Request
        run: |
          echo "Enabling access to AEH '${{ github.event.inputs.aeh_name }}' in '${{ github.event.inputs.resource_group }}' for project '${{ github.event.inputs.project_name }}' with UAIM '${{ github.event.inputs.uaim }}'
          
  create_aeh_within_project:
    # if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.inputs.resource_group && github.event.inputs.project_name && github.event.inputs.uaim && !github.event.inputs.aeh_name
    runs-on: ubuntu-latest
    steps:
      - name: Create AEH within Specific Project
        run: |
          echo "Creating AEH in '${{ github.event.inputs.resource_group }}' for project '${{ github.event.inputs.project_name }}' with UAIM '${{ github.event.inputs.uaim }}'"
     
  create_aeh_without_project:
    # if: success() && github.event_name == 'push' && github.ref == 'refs/heads/main' && github.event.inputs.resource_group && github.event.inputs.uaim && !github.event.inputs.project_name && !github.event.inputs.aeh_name
    runs-on: ubuntu-latest
    steps:
      - name: Create AEH without Project Name
        run: |
          echo "Creating AEH in '${{ github.event.inputs.resource_group }}' with shared namespace using UAIM '${{ github.event.inputs.uaim }}'"
