# .github/workflows/workflow-b.yml

name: Workflow B

on:
  workflow_dispatch:
    inputs:
      example_parameter:
        description: 'An example input parameter'
        required: true
        default: 'default_value'
      from_workflow_a:
        description: 'Triggered from Workflow A'
        required: false

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display example_parameter
        run: echo "This is Workflow B with example_parameter = ${{ github.event.inputs.example_parameter }}"

      - name: Trigger Workflow A via API
        if: ${{ github.event.inputs.from_workflow_a != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/nithinS10/Workflow-Learnings/actions/workflows/workflow-b.yml \
            -d '{"ref":"main", "inputs": {"example_parameter": "${{ github.event.inputs.example_parameter }}", "from_workflow_b": "true"}}'
