# .github/workflows/workflow-b.yml

name: Workflow B

on:
  workflow_dispatch:
    inputs:
      parameter1:
        description: 'An example input parameter'
        required: true
        default: 'default_value'

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display parameter1
        run: echo "This is Workflow B with parameter1 = ${{ github.event.inputs.parameter1 }}"
