# .github/workflows/workflow-a.yml

name: Workflow A

on:
  workflow_dispatch:
    inputs:
      example_parameter:
        description: 'An example input parameter'
        required: true
        default: 'default_value'
      from_workflow_b:
        description: 'Triggered from Workflow B'
        required: false

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Set output
        id: set_output
        run: echo "::set-output name=example_parameter::${{ github.event.inputs.example_parameter }}"
        
      - name: Trigger Workflow B via API
        if: ${{ github.event.inputs.from_workflow_b != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/nithinS10/Workflow-Learnings/actions/workflows/workflow-b.yml \
            -d '{"ref":"main", "inputs": {"example_parameter": "${{ steps.set_output.outputs.example_parameter }}", "from_workflow_a": "true"}}'
